### PR TITLE
Update phpunit, remove hhvm from travis

### PR DESCRIPTION
**Pull request by gpasztor87**

### CODE REVIEW

**Comment by scottbedard** [comment]
Out of curiosity, why remove hhvm? Is it no longer supported by Laravel or October?

**Comment by gpasztor87** [comment]
I don't know exactly, but it has been removed from October:
https://github.com/octobercms/october/commit/2424a6563d354bf0a6548cf832a34b5501a61b73

**Comment by gpasztor87** [comment]
I found that Laravel from 5.3 is no longer officially supported with HHVM : https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0

**Comment by scottbedard** [comment]
Ah, good catch, thanks!

**Pull request merged**
